In [1]:
import numpy as np 

In [12]:
a = np.array([3,2,3])

In [13]:
print ('print rank1 array:',a)

print rank1 array: [3 2 3]


In [14]:
print('print using index a[0]: ',a[0])

print using Slicing index a[0]:  3


In [15]:
a[0] = 5

In [16]:
print('print using Sclicing a[1:]: ',a[1:])

print using Sclicing a[1:]:  [2 3]


In [18]:
print('print the whole list :' , a)

print the whole list : [5 2 3]


In [21]:
#2D- Array
b = np.array([[10,20,30],[40,50,60]])
print('\n Print 2d np array: ',b)


 Print 2d np array:  [[10 20 30]
 [40 50 60]]


In [24]:
print('b[0][0] : ', b[0][0] , 'b[1][1] : ',b[1][1])

b[0][0] :  10 b[1][1] :  50


In [28]:
print(b[:1,2:])

[[30]]


In [30]:
A = np.zeros((2,2))
A

array([[0., 0.],
       [0., 0.]])

In [36]:
N = np.eye(4 , dtype = 'int')
N


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [38]:
V = np.full((3,3),6)
V

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [39]:
Z = np.ones((3,4),dtype = 'int')
Z


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [44]:
Z.shape


(3, 4)

In [49]:
Z.itemsize

4

In [50]:
Z.ndim

2

In [52]:
l = range(5)
l

range(0, 5)

In [53]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [56]:
print('concatination example :')
print(np.char.add(['Hello','Hi'],[' xyz',' abc']))

concatination example :
['Hello xyz' 'Hi abc']


In [ ]:
print(np.char.center(['Hello'],))