In [1]:
import numpy as np 

In [2]:
a = np.array([3,2,3])

In [3]:
print ('print rank1 array:',a)

print rank1 array: [3 2 3]


In [4]:
print('print using index a[0]: ',a[0])

print using index a[0]:  3


In [5]:
a[0] = 5

In [6]:
print('print using Sclicing a[1:]: ',a[1:])

print using Sclicing a[1:]:  [2 3]


In [7]:
print('print the whole list :' , a)

print the whole list : [5 2 3]


In [8]:
#2D- Array
b = np.array([[10,20,30],[40,50,60]])
print('\n Print 2d np array: ',b)


 Print 2d np array:  [[10 20 30]
 [40 50 60]]


In [9]:
print('b[0][0] : ', b[0][0] , 'b[1][1] : ',b[1][1])

b[0][0] :  10 b[1][1] :  50


In [10]:
print(b[:1,2:])

[[30]]


In [11]:
A = np.zeros((2,2))
A

array([[0., 0.],
       [0., 0.]])

In [12]:
N = np.eye(4 , dtype = 'int')
N


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [13]:
V = np.full((3,3),6)
V

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [14]:
Z = np.ones((3,4),dtype = 'int')
Z


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
Z.shape


(3, 4)

In [16]:
Z.itemsize

4

In [17]:
Z.ndim

2

In [18]:
l = range(5)
l

range(0, 5)

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
print('concatination example :')
print(np.char.add(['Hello','Hi'],[' xyz',' abc']))

concatination example :
['Hello xyz' 'Hi abc']


In [21]:
print(np.char.center([' Hello '],30,fillchar = '*'))

['*********** Hello ************']


In [22]:
print(np.char.multiply([' Hello '],3))

[' Hello  Hello  Hello ']


In [23]:
print(np.char.capitalize(['hello world']))

['Hello world']


In [24]:
print(np.char.upper((['Python','EASY'])))
print(np.char.lower((['Python','EASY'])))

['PYTHON' 'EASY']
['python' 'easy']


In [25]:
print(np.char.title((['Python','EASY'])))

['Python' 'Easy']


In [26]:
print(np.char.split(['are you coming back to party']))

[list(['are', 'you', 'coming', 'back', 'to', 'party'])]


In [27]:
print(np.char.splitlines('heloow\n how are you doing?'))

['heloow', ' how are you doing?']


In [28]:
print(np.char.strip(('nina','riya','dollya'),'a'))

['nin' 'riy' 'dolly']


In [29]:
print(np.char.join([':','-'],['dmy','ymd'])) # provinding dlimeter in a list,and list of strings

['d:m:y' 'y-m-d']


In [30]:
print(np.char.replace(['he is a good dancer','she is a cook'],'is','was'))

['he was a good dancer' 'she was a cook']


## <font color = grey > ARRAY MANIPULATION </font>

### <font color = red> changing shape </font>

In [31]:
import numpy as np 

In [35]:
A = np.arange(9)
print('The orignal array : ')
print(A)

The orignal array : 
[0 1 2 3 4 5 6 7 8]


In [36]:
B = A.reshape((3,3))
print('The modified array : ')
print(B)

The modified array : 
[[0 1 2]
 [3 4 5]
 [6 7 8]]



reshape